### PR TITLE
Add "Notebook" Layout

### LINKED ISSUE #164: Report/Notebook Layout
### Description

With the addition of the template & markdown nodes, it would be great to have a Dashboard layout that enabled more reporting/Notebook style Dashboards, with dynamic content.

1024px wide max-width, 100% on smaller screens. Groups stack atop each other, with content centralised.

### Have you provided an initial effort estimate for this issue?

I have provided an initial effort estimate

### PR DESCRIPTION
**Pull request by joepavitt**
## Description

Adds a new "Notebook" layout that has a max-width of 1024px, width 100% and centrally aligns. The styling is driven by the theme, with the background of the page and groups being defined by the relevant properties in the attached `ui-theme`.

## Related Issue(s)

Closes #164

## Checklist

 - [x] I have read the [contribution guidelines](https://github.com/flowforge/flowforge/blob/main/CONTRIBUTING.md)

### CODE REVIEW

**Comment by joepavitt** [comment]
Demo (manually duplicated some elements in browser to show scroll):

https://github.com/flowforge/flowforge-nr-dashboard/assets/99246719/6d0e0c62-135d-4a12-a0ae-aa3ba8e1bdbc

**Comment by joepavitt** [comment]
You can also still have elements sized based on the group width, e.g. here we have side-by-side charts:

Screenshot 2023-09-01 at 08 41 46

**Comment by joepavitt** [comment]
Group width behaviour does get a little unintuitive here though. Because I want the reports fixed widths, the group width just adds resolution to the report widths for it's contained widgets, e.g the above two-chart layout becomes:

Screenshot 2023-09-01 at 08 45 14

Where each chart has a "width" of 3, and the group now has 12 (previously 6)

**Comment by joepavitt** [comment]
would appreciate some thoughts on the group width behaviour @Steve-Mcl - I think it's okay, can't think of an alternative, happy to push as-is, and see what community feedback is like?

**Comment by joepavitt** [comment]
This is very fun:

layout-eg-notebook

**Comment by colinl** [comment]
Have you thought about how it will behave on printing?

**Comment by joepavitt** [comment]
> Have you thought about how it will behave on printing?

Very good point. A quick check suggests I've gone too wide with the default width of 1024px for a standard A4, but I'm fairly sure there are some print-mode only CSS tricks I can play with. Will give it a go.

**Comment by joepavitt** [comment]
Had a quick play @colinl and it's not totally trivial/easy, so will park it now as a [new issue](https://github.com/flowforge/flowforge-nr-dashboard/issues/166) to track.

**Review by Steve-Mcl — APPROVED** [review]

**Pull request merged**
