### PR TITLE
Adds ui-chart history-based state recording, adding time-axis, duration limit & fix line overshoot

### LINKED ISSUE #122: Server-Side State for Charts
### Description

https://github.com/flowforge/flowforge-nr-dashboard/issues/61 captured the need for server-side state management for all of our widgets. We do this by storing the latest `msg.payload` against each widget, however, for charts this doesn't encapsulate the full picture as we actually need to store a history of `msg.payloads`, or often a merger of payloads (e.g. if an array is provided with multiple data points), so we need to deep dive into charts specifically and identify, architecturally, how this can be achieved.

### Epic/Story

#61

### Have you provided an initial effort estimate for this issue?

I have provided an initial effort estimate

### LINKED ISSUE #172: Add 'Time' x-axis type for charts
### Description

We are currently missing a "Time" x-axis type for charts. This should likely be the default option too given that the most common use case for charts at the moment is sensor data visualisation.

### Have you provided an initial effort estimate for this issue?

I have provided an initial effort estimate

### LINKED ISSUE #173: Add Duration Option to Charts
### Description

See: https://discourse.nodered.org/t/dashboard-2-0-pre-alpha-available/80142/104?u=joepavitt

### Have you provided an initial effort estimate for this issue?

I have provided an initial effort estimate

### LINKED ISSUE #176: Chart - Data lines often overshoot data points
Dashboard v0.4.0
node-RED v 3.1.0
Ubuntu cloud server

Injecting random date into a chart node appears to result in the data line often overshooting the actual data point.

chart

The data points appear to be positioned correctly.

Reported in forum - https://discourse.nodered.org/t/dashboard-2-0-pre-alpha-available/80142/118 (together with comments about the line thickness).

Example flow...
```
[{"id":"3ae226c1cdb40ba0","type":"ui-chart","z":"51a81bf279dcf161","group":"72d0d297dc80bc0f","name":"","label":"chart","order":6,"chartType":"line","xAxisType":"linear","width":"14","height":"8","className":"","x":610,"y":220,"wires":[[]]},{"id":"ae966f9fe2e16c8c","type":"inject","z":"51a81bf279dcf161","name":"","props":[{"p":"payload"},{"p":"topic","vt":"str"}],"repeat":"","crontab":"","once":false,"onceDelay":0.1,"topic":"","payload":"","payloadType":"date","x":220,"y":220,"wires":[["c2acca6d1833d5d7"]]},{"id":"c2acca6d1833d5d7","type":"function","z":"51a81bf279dcf161","name":"function 1","func":"msg.payload = Math.floor(Math.random() * (100 - 50 + 1)) + 50\nreturn msg","outputs":1,"noerr":0,"initialize":"","finalize":"","libs":[],"x":420,"y":220,"wires":[["3ae226c1cdb40ba0"]]},{"id":"72d0d297dc80bc0f","type":"ui-group","name":"My group","page":"d3491e273d04f272","width":"15","height":"8","order":"","disp":true},{"id":"d3491e273d04f272","type":"ui-page","name":"Test","ui":"052a612d0e57bc06","path":"/","layout":"grid","theme":"792775d090ad7f74"},{"id":"052a612d0e57bc06","type":"ui-base","name":"UI Name","path":"/dashboard"},{"id":"792775d090ad7f74","type":"ui-theme","name":"mytheme","colors":{"surface":"#ffffff","primary":"#0094ce","bgPage":"#eeeeee","groupBg":"#ffffff","groupOutline":"#cccccc"}}]
```

### PR DESCRIPTION
**Pull request by joepavitt**
## Description

- Custom server-side `onInput` for `ui-chart` so that we can handle the appending of `msg` to `_msg`, rather than replacement.
- Add a `beforeSend` server-side to process `msg` on a chart and add `msg._datapoint` so that we maintain context of x/y data (this was previously client-side and so we lost any added time data on the x-axis, as only had `msg.payload`)
- Clear history when receiving `[]` in `msg.payload`
- Turn off animation in ChartJS (when receiving quick data, causes delays)
- Adds "Timescale" option for x-axis (now default) as it's the most common use case in Dashboard 1.0
   - Needed to add a [Datetime Adapter](https://github.com/chartjs/awesome#adapters) for this to work, chose `luxon` as it seemed lightest and actually worked (`spacetime` didn't)
- Data size limitations:
    - Treats history management differently for different charts types:
        - Line/Scatter - limits per line
        - Bar - categorical limits, only stores latest value for each bar 

## Related Issue(s)

Fixes #122

https://github.com/flowforge/flowforge-nr-dashboard/assets/99246719/a72dad48-0b33-4620-afb7-3a4b31d5c7d6

Fixes #172 - "Add 'Time' x-axis option" 

Screenshot 2023-09-14 at 10 19 12

Fixes #176 - "Data overshoots data points"

Screenshot 2023-09-13 at 13 39 32

Fixes #173 - "Add duration limit to charts"

https://github.com/flowforge/flowforge-nr-dashboard/assets/99246719/58e1d22d-d044-455b-8ac5-667417f5e973

## Checklist

 - [x] I have read the [contribution guidelines](https://github.com/flowforge/flowforge/blob/main/CONTRIBUTING.md)
 - [ ] Suitable unit/system level tests have been added and they pass 
 - [x] Documentation has been updated
    - [ ] Upgrade instructions
    - [ ] Configuration details
    - [ ] Concepts
 - [ ] Changes `flowforge.yml`?
    - [ ] Issue/PR raised on `flowforge/helm` to update ConfigMap Template
    - [ ] Issue/PR raised on `flowforge/CloudProject` to update values for Staging/Production

## Labels

 - [ ] Backport needed? -> add the `backport` label
 - [ ] Includes a DB migration? -> add the `area:migration` label

### CODE REVIEW

**Comment by Paul-Reed** [comment]
Hi @joepavitt - noticed that when selecting;

- The 'last time period  **OR**
- The number of points

It's not possible to limit the charts solely by the number of points, as the red warning triangle suggests that both need to be set.

chart

**Comment by joepavitt** [comment]
Ah, thank you for spotting. Won't be able to fix that today unfortunately, but short term would be to set that to very high value, so that points aren't cut

**Comment by joepavitt** [comment]
Just checked Dashboars 1.0, and this behaves exactly the same fwiw.

Agree the "or" suggests optional though

**Comment by Paul-Reed** [comment]
Ah OK. I haven't used the node-RED dashboard for a few years now, so haven't compared.
Thanks.

**Pull request merged**
