### PR TITLE
Introduce publish package pipeline

### PR DESCRIPTION
**Pull request by ppawlowski**
## Description

Introduce package build and publish pipeline. At this stage, publishing is made only to the internal NPM registry.

## Related Issue(s)

https://github.com/flowforge/flowforge-nr-dashboard/issues/133

## Checklist

 - [x] I have read the [contribution guidelines](https://github.com/flowforge/flowforge/blob/main/CONTRIBUTING.md)
 - [ ] Suitable unit/system level tests have been added and they pass 
 - [ ] Documentation has been updated
    - [ ] Upgrade instructions
    - [ ] Configuration details
    - [ ] Concepts
 - [ ] Changes `flowforge.yml`?
    - [ ] Issue/PR raised on `flowforge/helm` to update ConfigMap Template
    - [ ] Issue/PR raised on `flowforge/CloudProject` to update values for Staging/Production

## Labels

 - [ ] Backport needed? -> add the `backport` label
 - [ ] Includes a DB migration? -> add the `area:migration` label

### CODE REVIEW

**Comment by hardillb** [comment]
Once this is merged we will need to also update the release action to publish full releases to the private repo as well

**Comment by hardillb** [comment]
@joepavitt do we expect these tests to fail at the moment?

**Comment by joepavitt** [comment]
Nope

**Comment by ppawlowski** [comment]
> Once this is merged we will need to also update the release action to publish full releases to the private repo as well
> 
> https://github.com/flowforge/flowforge-nr-dashboard/blob/main/.github/workflows/publish-release.yml

Change available [here](https://github.com/flowforge/flowforge-nr-dashboard/pull/140).

**Comment by joepavitt** [comment]
Not sure why this has triggered those tests to fail, need to investigate

**Comment by joepavitt** [comment]
Tests fixed in #146 but I also would like to rename this a little better, as we do [already have](https://github.com/flowforge/flowforge-nr-dashboard/blob/main/.github/workflows/publish-release.yml) a `Publish & Release` workflow for publishing the to public repository.

If I understand correctly, a more appropriate name for this workflow would be `publish-ff-private` or something like that? Do we also need to update the `flowforge` usage here too, since the rebrand?

**Comment by ppawlowski** [comment]
The name of the workflow has been updated.

> Do we also need to update the `flowforge` usage here too, since the rebrand?

`flowfroge` reference in the workflow is the name of the GitHub organisation. We will update it everywhere once we rename it.

**Comment by hardillb** [comment]
Apart from that dashboard content appears to have snuck in here as well, is this good to merge now?

**Comment by ppawlowski** [comment]
Maybe let's merge #146 first.

**Comment by joepavitt** [comment]
My reasoning for wanting to split the workflows is because of this:

Screenshot 2023-08-29 at 12 34 29

We now have these workflows labelled accordingly running for every PR, but the labelling doesn't reflect what is actually happening.

Here, it's just running the `build and test`. In another instance, where we are pushing/merging to `main`, then that labelling is appropriate.

**Review by joepavitt — APPROVED** [review]

**Pull request merged**
